baseURL = "http://adaptiveprogrammer.com"
languageCode = "en"
title = "Adaptive Programmer"
theme = "hugo-nuo"
enableRobotsTXT = true
pygmentsUseClasses = false
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
canonifyurls = true

# Disqus Username
disqusShortname = "adaptive-programmer"

# Google Analytics UA number
googleAnalytics = "UA-XXXXXXXX-X"

# Copyright of your post
copyright = "© Copyright 2017 - AdaptiveProgrammer.com - Learn. Adapt. Build. Thrive."

# Add your own params here
[params]
  author = "Peter Puglisi"
  avatar = "/img/logo.png"
  seotitle = "Adaptive Programmer - Modern Agile Transformation and Adaptive Software Engineering"
  subtitle = "Learn. Adapt. Build. Thrive."
  description = "A veteran software developer's blog about riding the wave of modern agile transformation. Bloggers mindset: Be happy and satisfied today and always be eager for more."
  paginate = 10

  # Choose your social networks
  email = "peter@peterpuglisi.com"
  github = "peterpuglisi"
  twitter = "puglisi_peter"
  linkedin = "peterpuglisi"